name: DibLib-Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/dibrysoft/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GH_TOKEN}}
          
      - id: get_version
        uses: battila7/get-version-action@v2
          
      - run: dotnet build diblib/diblib.csproj --configuration Release /p:Version=${{ steps.get_version.outputs.version-without-v }}
      - name: Create the package
        run: dotnet pack diblib/diblib.csproj --configuration Release /p:Version=${{ steps.get_version.outputs.version-without-v }}
      - name: Publish to github
        run: dotnet nuget push diblib/bin/Release/*.nupkg  -k ${{ secrets.GH_TOKEN }} -s https://nuget.pkg.github.com/DibrySoft/index.json --skip-duplicate
